### ISSUE TITLE
vscode not connecting docker's remote container

### ISSUE THREAD

**Issue by SeijiOkuda** [SeijiOkuda/docker-Java#7]
occurring in the #6 feature/okuda branch
# execute vscode **Reopen In Container**
C:\Users\okuda\OkudasLoacleDocuments\00_localRep\docker-Java

# An error is displayed.
![image](https://github.com/SeijiOkuda/docker-Java/assets/117446008/c2db62e3-1cb5-402b-a915-a6201046b442)
# Logs
[remoteContainers-2023-08-16T14-19-05.928Z.log](https://github.com/SeijiOkuda/docker-Java/files/12360425/remoteContainers-2023-08-16T14-19-05.928Z.log)

**Comment by SeijiOkuda** [comment]
# Environment
OS：Windows 10 22H2
docker：Docker Desktop for Windows 4.22.0
vscode：1.81.1
　vscpde extension：
　　Name: Dev Containers
　　Id: ms-vscode-remote.remote-containers
　　Description: Open any folder or repository inside a Docker container and take advantage of Visual Studio Code's full feature set.
　　Version: 0.304.0
　　Publisher: Microsoft
　　VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

**Comment by juner** [comment]
see.
not found remote user : `vscode`
not found workspace path: `/workspace`

**Comment by SeijiOkuda** [comment]
@juner  Thanks.
I've tried modifying it like this, what do you think?
608de26

**Comment by SeijiOkuda** [comment]
@juner 
like this? 0a8d154

**Comment by juner** [comment]
@SeijiOkuda 
I haven't tested it, but I think it should work.
